# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import device_data_pb2 as device__data__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in device_data_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DeviceDataServiceStub(object):
    """============================================================
    设备实时数据服务
    - Subscribe : 服务端流式 RPC，持续推送 DataFrame
    - SendCommand: 一元 RPC，发送控制指令并等待响应
    ============================================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Subscribe = channel.unary_stream(
                '/device_data.DeviceDataService/Subscribe',
                request_serializer=device__data__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=device__data__pb2.DataFrame.FromString,
                _registered_method=True)
        self.SendCommand = channel.unary_unary(
                '/device_data.DeviceDataService/SendCommand',
                request_serializer=device__data__pb2.CommandRequest.SerializeToString,
                response_deserializer=device__data__pb2.CommandResponse.FromString,
                _registered_method=True)


class DeviceDataServiceServicer(object):
    """============================================================
    设备实时数据服务
    - Subscribe : 服务端流式 RPC，持续推送 DataFrame
    - SendCommand: 一元 RPC，发送控制指令并等待响应
    ============================================================
    """

    def Subscribe(self, request, context):
        """订阅实时数据流（Server-Streaming）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendCommand(self, request, context):
        """发送控制指令
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DeviceDataServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=device__data__pb2.SubscribeRequest.FromString,
                    response_serializer=device__data__pb2.DataFrame.SerializeToString,
            ),
            'SendCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.SendCommand,
                    request_deserializer=device__data__pb2.CommandRequest.FromString,
                    response_serializer=device__data__pb2.CommandResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'device_data.DeviceDataService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('device_data.DeviceDataService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DeviceDataService(object):
    """============================================================
    设备实时数据服务
    - Subscribe : 服务端流式 RPC，持续推送 DataFrame
    - SendCommand: 一元 RPC，发送控制指令并等待响应
    ============================================================
    """

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/device_data.DeviceDataService/Subscribe',
            device__data__pb2.SubscribeRequest.SerializeToString,
            device__data__pb2.DataFrame.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/device_data.DeviceDataService/SendCommand',
            device__data__pb2.CommandRequest.SerializeToString,
            device__data__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
