# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: device_data.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'device_data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x64\x65vice_data.proto\x12\x0b\x64\x65vice_data\">\n\x10SubscribeRequest\x12\x15\n\rchannel_count\x18\x01 \x01(\r\x12\x13\n\x0binterval_ms\x18\x02 \x01(\r\"\x8c\x01\n\tDataFrame\x12\x11\n\ttimestamp\x18\x01 \x01(\x04\x12\x10\n\x08\x66rame_id\x18\x02 \x01(\r\x12\x13\n\x0b\x64\x65tect_mode\x18\x03 \x01(\r\x12\x15\n\rchannel_count\x18\x04 \x01(\r\x12\x16\n\x0e\x63hannels_comp0\x18\x05 \x03(\x01\x12\x16\n\x0e\x63hannels_comp1\x18\x06 \x03(\x01\"5\n\x0e\x43ommandRequest\x12\x0f\n\x07payload\x18\x01 \x01(\x0c\x12\x12\n\ncommand_id\x18\x02 \x01(\t\"G\n\x0f\x43ommandResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x12\n\ncommand_id\x18\x03 \x01(\t2\xa3\x01\n\x11\x44\x65viceDataService\x12\x44\n\tSubscribe\x12\x1d.device_data.SubscribeRequest\x1a\x16.device_data.DataFrame0\x01\x12H\n\x0bSendCommand\x12\x1b.device_data.CommandRequest\x1a\x1c.device_data.CommandResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'device_data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SUBSCRIBEREQUEST']._serialized_start=34
  _globals['_SUBSCRIBEREQUEST']._serialized_end=96
  _globals['_DATAFRAME']._serialized_start=99
  _globals['_DATAFRAME']._serialized_end=239
  _globals['_COMMANDREQUEST']._serialized_start=241
  _globals['_COMMANDREQUEST']._serialized_end=294
  _globals['_COMMANDRESPONSE']._serialized_start=296
  _globals['_COMMANDRESPONSE']._serialized_end=367
  _globals['_DEVICEDATASERVICE']._serialized_start=370
  _globals['_DEVICEDATASERVICE']._serialized_end=533
# @@protoc_insertion_point(module_scope)
